const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const supabase = createClient(supabaseUrl, serviceRoleKey);

async function runTest() {
  console.log("=== STARTING INTEGRATION TEST ===");

  const dummyEmail = `test_${Date.now()}@nexhrms.com`;
  const dummyPassword = "Password123!";

  try {
    // 1. Create a dummy Auth User
    console.log("1. Creating dummy auth user...");
    const { data: authData, error: authErr } = await supabase.auth.admin.createUser({
      email: dummyEmail,
      password: dummyPassword,
      email_confirm: true
    });
    if (authErr) throw new Error("Auth Error: " + authErr.message);
    const userId = authData.user.id;

    // 2. Insert dummy Employee
    console.log("2. Creating dummy employee profile...");
    const empId = `EMP-TEST-${Date.now()}`;
    const { error: empErr } = await supabase.from('employees').insert({
      id: empId,
      profile_id: userId,
      name: "Test Mobile User",
      email: dummyEmail,
      attendance_method: "mobile_gps_only",
      status: "active",
      role: "employee"
    });
    if (empErr) throw new Error("Employee Error: " + empErr.message);

    // 3. Create dummy Company
    const compId = `COMP-TEST-${Date.now()}`;
    await supabase.from('companies').insert({
      id: compId,
      name: "Test Company"
    });
    
    // We update employee company_id
    await supabase.from('employees').update({ company_id: compId }).eq('id', empId);

    // 4. Create Work Location
    console.log("3. Creating work location (Makati HQ)...");
    const locId = `WL-TEST-${Date.now()}`;
    const { error: locErr } = await supabase.from('work_locations').insert({
      id: locId,
      company_id: compId,
      location_name: "Makati HQ Test",
      latitude: 14.5547,
      longitude: 121.0244,
      allowed_radius_meters: 100
    });
    if (locErr && locErr.code !== '42P01') throw new Error("Work Location Error: " + locErr.message);

    // 5. Assign Work Location
    if (!locErr) {
      await supabase.from('employee_work_locations').insert({
        employee_id: empId,
        work_location_id: locId,
        is_primary: true
      });
    }

    // 6. Login to get JWT
    console.log("4. Logging in as dummy user...");
    const { data: loginData, error: loginErr } = await supabase.auth.signInWithPassword({
      email: dummyEmail,
      password: dummyPassword
    });
    if (loginErr) throw new Error("Login Error: " + loginErr.message);
    const token = loginData.session.access_token;

    // 7. Test Mobile Attendance API (Inside Geofence)
    console.log("5. Testing Mobile Clock-In (INSIDE Geofence)...");
    const port = 3001; // NexHRMS-v2 is likely running on 3001 because PremiumOutlet is on 3000
    const resInside = await fetch(`http://localhost:${port}/api/attendance/mobile`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${token}` },
      body: JSON.stringify({
        latitude: 14.5547, // Exact same coordinates
        longitude: 121.0244,
        gpsAccuracyMeters: 5,
        deviceId: "TEST-DEVICE-01"
      })
    });
    
    let insideData;
    try {
      insideData = await resInside.json();
    } catch(e) {
      const text = await resInside.text();
      throw new Error(`Non-JSON Response from API. Port might be wrong. Server said: ${text.substring(0, 50)}...`);
    }
    console.log("   -> API Response:", insideData);

    // 8. Test Mobile Attendance API (Outside Geofence) - 1 hour later
    console.log("6. Testing Mobile Clock-Out (OUTSIDE Geofence)...");
    
    // Fast forward 2 hours for checkout
    const checkOutDate = new Date();
    checkOutDate.setHours(checkOutDate.getHours() + 2);

    const resOutside = await fetch(`http://localhost:${port}/api/attendance/mobile`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${token}` },
      body: JSON.stringify({
        latitude: 10.3157, // Cebu City
        longitude: 123.8854,
        gpsAccuracyMeters: 5,
        deviceId: "TEST-DEVICE-01",
        timestampUTC: checkOutDate.toISOString()
      })
    });
    const outsideData = await resOutside.json();
    console.log("   -> API Response:", outsideData);

    // 9. Verify Overtime Computation
    console.log("7. Verifying Overtime Generation...");
    // We can manually trigger the OT computation for this user if there's an API, 
    // or we just query ot_records
    const { data: otData } = await supabase.from('ot_records').select('*').eq('employee_id', empId);
    console.log(`   -> Found ${otData ? otData.length : 0} OT records for this employee.`);
    if (otData && otData.length === 0) {
       console.log("   -> (OT is typically generated by a cron job or HR review step, so 0 is expected immediately after clock out).");
    }

    console.log("=== INTEGRATION TEST COMPLETED SUCCESSFULLY ===");

    // Clean up
    console.log("8. Cleaning up test data...");
    await supabase.from('employee_work_locations').delete().eq('employee_id', empId);
    await supabase.from('work_locations').delete().eq('id', locId);
    await supabase.from('employees').delete().eq('id', empId);
    await supabase.auth.admin.deleteUser(userId);

  } catch (err) {
    console.error("Test failed:", err.message);
  }
}

runTest();
