"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useAuthStore } from "@/store/auth.store";
import { useEmployeesStore } from "@/store/employees.store";
import { useAttendanceStore } from "@/store/attendance.store";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import {
  AlertTriangle,
  CalendarDays,
  CheckCircle2,
  Clock3,
  Download,
  FileWarning,
  Fingerprint,
  ScanFace,
  ShieldCheck,
  Timer,
  XCircle,
} from "lucide-react";
import { toast } from "sonner";

const METHODS = ["fingerprint", "face", "palm", "rfid", "pin"] as const;
const EXCEPTION_FLAGS = [
  "missing_in",
  "missing_out",
  "duplicate_scan",
  "device_mismatch",
  "late_arrival",
  "early_departure",
  "overtime_without_approval",
  "out_of_geofence",
  "suspicious_activity",
] as const;

type EnrollmentRow = {
  id: string;
  method: string;
  enrolled_at: string;
  is_active: boolean;
  enrolled_by_employee?: { id: string; name: string; email: string };
};

type BiometricLogRow = {
  id: string;
  recognition_method: string;
  log_type: "time_in" | "time_out";
  logged_at: string;
  confidence_score?: number | null;
  low_confidence: boolean;
  device?: { id: string; name: string; location?: string; device_type?: string };
};

type ExceptionRow = {
  id: string;
  employeeId: string;
  date: string;
  flag: string;
  autoGenerated: boolean;
  resolvedAt?: string | null;
  notes?: string | null;
  createdAt: string;
};

function formatDate(isoOrDate: string) {
  return new Date(isoOrDate).toLocaleDateString("en-PH", {
    timeZone: "Asia/Manila",
    month: "short",
    day: "2-digit",
    year: "numeric",
  });
}

function formatTime(iso: string) {
  return new Date(iso).toLocaleTimeString("en-PH", {
    timeZone: "Asia/Manila",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function prettify(value: string) {
  return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function formatDateInputValue(date: Date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export default function MyBiometricPage() {
  const currentUser = useAuthStore((s) => s.currentUser);
  const employees = useEmployeesStore((s) => s.employees);
  const attendanceLogs = useAttendanceStore((s) => s.logs);
  const shiftTemplates = useAttendanceStore((s) => s.shiftTemplates);
  const employeeShifts = useAttendanceStore((s) => s.employeeShifts);

  const [enrollments, setEnrollments] = useState<EnrollmentRow[]>([]);
  const [biometricLogs, setBiometricLogs] = useState<BiometricLogRow[]>([]);
  const [exceptions, setExceptions] = useState<ExceptionRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [dateFrom, setDateFrom] = useState(() => {
    const now = new Date();
    return formatDateInputValue(new Date(now.getFullYear(), now.getMonth(), 1));
  });
  const [dateTo, setDateTo] = useState(() => formatDateInputValue(new Date()));
  const [exceptionDate, setExceptionDate] = useState(() => formatDateInputValue(new Date()));
  const [exceptionFlag, setExceptionFlag] = useState<(typeof EXCEPTION_FLAGS)[number]>("missing_in");
  const [exceptionNotes, setExceptionNotes] = useState("");

  const myEmployee = useMemo(() => {
    return employees.find(
      (employee) =>
        employee.profileId === currentUser.id ||
        employee.id === currentUser.id ||
        employee.email?.toLowerCase() === currentUser.email?.toLowerCase() ||
        employee.name === currentUser.name
    );
  }, [employees, currentUser]);

  const myAttendanceLogs = useMemo(() => {
    if (!myEmployee) return [];
    return attendanceLogs
      .filter((log) => log.employeeId === myEmployee.id && log.date >= dateFrom && log.date <= dateTo)
      .sort((a, b) => b.date.localeCompare(a.date));
  }, [attendanceLogs, dateFrom, dateTo, myEmployee]);

  const activeEnrollmentMap = useMemo(() => {
    const map: Record<string, EnrollmentRow> = {};
    enrollments.forEach((enrollment) => {
      if (enrollment.is_active) map[enrollment.method] = enrollment;
    });
    return map;
  }, [enrollments]);

  const assignedShift = useMemo(() => {
    if (!myEmployee) return undefined;
    const shiftId = employeeShifts[myEmployee.id] || myEmployee.shiftId;
    return shiftTemplates.find((shift) => shift.id === shiftId) || shiftTemplates[0];
  }, [employeeShifts, myEmployee, shiftTemplates]);

  const summary = useMemo(() => {
    const totalHours = myAttendanceLogs.reduce((sum, log) => sum + (Number(log.hours) || 0), 0);
    const lateMinutes = myAttendanceLogs.reduce((sum, log) => sum + (Number(log.lateMinutes) || 0), 0);
    const presentDays = myAttendanceLogs.filter((log) => log.status === "present").length;
    const unresolvedExceptions = exceptions.filter((exception) => !exception.resolvedAt).length;
    return { totalHours, lateMinutes, presentDays, unresolvedExceptions };
  }, [exceptions, myAttendanceLogs]);

  const loadEmployeeBiometrics = useCallback(async () => {
    if (!myEmployee) return;
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (dateFrom) params.set("date_from", dateFrom);
      if (dateTo) params.set("date_to", dateTo);

      const [enrollmentsRes, logsRes, exceptionsRes] = await Promise.all([
        fetch(`/api/biometric/enrollments/${myEmployee.id}`),
        fetch(`/api/biometric/logs/${myEmployee.id}?${params.toString()}`),
        fetch(`/api/attendance/exceptions?employeeId=${encodeURIComponent(myEmployee.id)}`),
      ]);

      const enrollmentsData = await enrollmentsRes.json();
      const logsData = await logsRes.json();
      const exceptionsData = await exceptionsRes.json();

      if (!enrollmentsRes.ok) throw new Error(enrollmentsData.error || "Failed to load enrollment status");
      if (!logsRes.ok) throw new Error(logsData.error || "Failed to load biometric logs");
      if (!exceptionsRes.ok) throw new Error(exceptionsData.error || "Failed to load exceptions");

      setEnrollments(Array.isArray(enrollmentsData) ? enrollmentsData : []);
      setBiometricLogs(Array.isArray(logsData) ? logsData : []);
      setExceptions(Array.isArray(exceptionsData.data) ? exceptionsData.data : []);
    } catch (error) {
      console.error(error);
      toast.error(error instanceof Error ? error.message : "Failed to load biometric data");
    } finally {
      setLoading(false);
    }
  }, [dateFrom, dateTo, myEmployee]);

  useEffect(() => {
    if (!myEmployee) return;
    void loadEmployeeBiometrics();
  }, [loadEmployeeBiometrics, myEmployee]);

  const submitException = async () => {
    if (!myEmployee) return;
    if (!exceptionDate) {
      toast.error("Select a date");
      return;
    }
    if (exceptionNotes.trim().length < 5) {
      toast.error("Add a short note for HR");
      return;
    }

    try {
      const res = await fetch("/api/attendance/exceptions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          employeeId: myEmployee.id,
          date: exceptionDate,
          flag: exceptionFlag,
          notes: exceptionNotes.trim(),
          autoGenerated: false,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to submit request");
      toast.success("Exception request submitted");
      setExceptionNotes("");
      await loadEmployeeBiometrics();
    } catch (error) {
      console.error(error);
      toast.error(error instanceof Error ? error.message : "Failed to submit request");
    }
  };

  const exportCsv = () => {
    if (biometricLogs.length === 0) return;
    const rows = [
      ["Date", "Time", "Type", "Method", "Device", "Confidence", "Low Confidence"],
      ...biometricLogs.map((log) => [
        formatDate(log.logged_at),
        formatTime(log.logged_at),
        log.log_type,
        log.recognition_method,
        log.device?.name || "",
        log.confidence_score ?? "",
        log.low_confidence ? "yes" : "no",
      ]),
    ];
    const csv = rows.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const anchor = document.createElement("a");
    anchor.href = URL.createObjectURL(blob);
    anchor.download = `my-biometric-logs-${formatDateInputValue(new Date())}.csv`;
    anchor.click();
    URL.revokeObjectURL(anchor.href);
  };

  if (!myEmployee) {
    return (
      <div className="p-6">
        <Card>
          <CardContent className="p-6 text-sm text-muted-foreground">
            We could not match your account to an employee record.
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-6 space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold">My Biometric Attendance</h1>
          <p className="text-sm text-muted-foreground">Attendance logs, enrollment status, DTR summary, and correction requests</p>
        </div>
        <Button variant="outline" className="gap-2 sm:w-auto" onClick={exportCsv} disabled={biometricLogs.length === 0}>
          <Download className="h-4 w-4" /> Export Logs
        </Button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Present Days</p>
              <p className="text-2xl font-bold">{summary.presentDays}</p>
            </div>
            <CalendarDays className="h-6 w-6 text-blue-500" />
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Worked Hours</p>
              <p className="text-2xl font-bold">{summary.totalHours.toFixed(1)}</p>
            </div>
            <Timer className="h-6 w-6 text-emerald-500" />
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Late Minutes</p>
              <p className="text-2xl font-bold">{summary.lateMinutes}</p>
            </div>
            <Clock3 className="h-6 w-6 text-amber-500" />
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Open Requests</p>
              <p className="text-2xl font-bold">{summary.unresolvedExceptions}</p>
            </div>
            <FileWarning className="h-6 w-6 text-red-500" />
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardContent className="p-4 flex flex-col gap-3 lg:flex-row lg:items-center">
          <div className="flex flex-col gap-2 sm:flex-row">
            <Input type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} className="sm:w-[170px]" />
            <Input type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} className="sm:w-[170px]" />
          </div>
          <div className="text-xs text-muted-foreground lg:ml-auto">
            {loading ? "Refreshing..." : `${biometricLogs.length} biometric scan(s) loaded`}
          </div>
        </CardContent>
      </Card>

      <Tabs defaultValue="logs" className="space-y-4">
        <TabsList className="grid w-full grid-cols-4 lg:w-[560px]">
          <TabsTrigger value="logs">Logs</TabsTrigger>
          <TabsTrigger value="dtr">DTR</TabsTrigger>
          <TabsTrigger value="enrollment">Enrollment</TabsTrigger>
          <TabsTrigger value="requests">Requests</TabsTrigger>
        </TabsList>

        <TabsContent value="logs">
          <Card>
            <CardHeader><CardTitle className="text-base">Biometric Scan History</CardTitle></CardHeader>
            <CardContent className="p-0 overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead>Time</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Method</TableHead>
                    <TableHead>Device</TableHead>
                    <TableHead>Flags</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {biometricLogs.length === 0 ? (
                    <TableRow><TableCell colSpan={6} className="py-6 text-center text-muted-foreground">No biometric scans found</TableCell></TableRow>
                  ) : biometricLogs.map((log) => (
                    <TableRow key={log.id}>
                      <TableCell>{formatDate(log.logged_at)}</TableCell>
                      <TableCell>{formatTime(log.logged_at)}</TableCell>
                      <TableCell>{log.log_type === "time_in" ? "Time In" : "Time Out"}</TableCell>
                      <TableCell><Badge variant="outline">{prettify(log.recognition_method)}</Badge></TableCell>
                      <TableCell>{log.device?.name || "-"}</TableCell>
                      <TableCell>
                        {log.low_confidence ? (
                          <Badge variant="outline" className="text-amber-600">Low confidence</Badge>
                        ) : (
                          <span className="text-muted-foreground">-</span>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="dtr">
          <div className="grid grid-cols-1 xl:grid-cols-[1fr_320px] gap-4">
            <Card>
              <CardHeader><CardTitle className="text-base">Daily Time Record</CardTitle></CardHeader>
              <CardContent className="p-0 overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>In</TableHead>
                      <TableHead>Out</TableHead>
                      <TableHead>Hours</TableHead>
                      <TableHead>OT</TableHead>
                      <TableHead>Late</TableHead>
                      <TableHead>Status</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {myAttendanceLogs.length === 0 ? (
                      <TableRow><TableCell colSpan={6} className="py-6 text-center text-muted-foreground">No DTR records found</TableCell></TableRow>
                    ) : myAttendanceLogs.map((log) => (
                      <TableRow key={log.id}>
                        <TableCell>{formatDate(`${log.date}T00:00:00+08:00`)}</TableCell>
                        <TableCell>{log.checkIn || "-"}</TableCell>
                        <TableCell>{log.checkOut || "-"}</TableCell>
                        <TableCell>{log.hours ?? "-"}</TableCell>
                        <TableCell>{log.otHours ?? 0}</TableCell>
                        <TableCell>{log.lateMinutes ?? 0} min</TableCell>
                        <TableCell><Badge variant="outline">{prettify(log.status)}</Badge></TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle className="text-base">Assigned Shift</CardTitle></CardHeader>
              <CardContent className="space-y-3 text-sm">
                {assignedShift ? (
                  <>
                    <div className="flex items-center justify-between"><span className="text-muted-foreground">Name</span><span className="font-medium">{assignedShift.name}</span></div>
                    <div className="flex items-center justify-between"><span className="text-muted-foreground">Time</span><span className="font-medium">{assignedShift.startTime} - {assignedShift.endTime}</span></div>
                    <div className="flex items-center justify-between"><span className="text-muted-foreground">Grace</span><span className="font-medium">{assignedShift.gracePeriod} min</span></div>
                    <div className="flex items-center justify-between"><span className="text-muted-foreground">Break</span><span className="font-medium">{assignedShift.breakDuration} min</span></div>
                  </>
                ) : (
                  <p className="text-muted-foreground">No shift assigned</p>
                )}
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="enrollment">
          <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-4">
            {METHODS.map((method) => {
              const enrollment = activeEnrollmentMap[method];
              const Icon = method === "face" ? ScanFace : method === "fingerprint" || method === "palm" ? Fingerprint : ShieldCheck;
              return (
                <Card key={method} className={enrollment ? "border-emerald-200" : "border-dashed"}>
                  <CardContent className="p-4 space-y-3">
                    <div className="flex items-center justify-between">
                      <Icon className={enrollment ? "h-5 w-5 text-emerald-500" : "h-5 w-5 text-muted-foreground"} />
                      {enrollment ? <CheckCircle2 className="h-5 w-5 text-emerald-500" /> : <XCircle className="h-5 w-5 text-red-500" />}
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">{method.toUpperCase()}</p>
                      <p className="text-lg font-semibold">{enrollment ? "Enrolled" : "Not Enrolled"}</p>
                      {enrollment?.enrolled_at && <p className="text-xs text-muted-foreground mt-1">{formatDate(enrollment.enrolled_at)}</p>}
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </TabsContent>

        <TabsContent value="requests">
          <div className="grid grid-cols-1 xl:grid-cols-[380px_1fr] gap-4">
            <Card>
              <CardHeader><CardTitle className="text-base">Request Correction</CardTitle></CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">Date</label>
                  <Input type="date" value={exceptionDate} onChange={(event) => setExceptionDate(event.target.value)} />
                </div>
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">Issue</label>
                  <Select value={exceptionFlag} onValueChange={(value) => setExceptionFlag(value as typeof exceptionFlag)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {EXCEPTION_FLAGS.map((flag) => (
                        <SelectItem key={flag} value={flag}>{prettify(flag)}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1.5">
                  <label className="text-sm font-medium">Note</label>
                  <Textarea value={exceptionNotes} onChange={(event) => setExceptionNotes(event.target.value)} placeholder="Explain what HR should review" rows={4} />
                </div>
                <Button className="w-full gap-2" onClick={submitException}>
                  <AlertTriangle className="h-4 w-4" /> Submit Request
                </Button>
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle className="text-base">My Exception Requests</CardTitle></CardHeader>
              <CardContent className="p-0 overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>Issue</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Note</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {exceptions.length === 0 ? (
                      <TableRow><TableCell colSpan={4} className="py-6 text-center text-muted-foreground">No exception requests found</TableCell></TableRow>
                    ) : exceptions.map((exception) => (
                      <TableRow key={exception.id}>
                        <TableCell>{formatDate(`${exception.date}T00:00:00+08:00`)}</TableCell>
                        <TableCell>{prettify(exception.flag)}</TableCell>
                        <TableCell>
                          <Badge variant="outline" className={exception.resolvedAt ? "text-emerald-600" : "text-amber-600"}>
                            {exception.resolvedAt ? "Resolved" : "Pending"}
                          </Badge>
                        </TableCell>
                        <TableCell className="max-w-[360px] truncate">{exception.notes || "-"}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
